import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root",
})
export class EditActionDataService {
  constructor() {}

  Users = {
    ResponseCode: "00",
    Data: {
      userId: 7,
      userTypeName: null,
      userTypeId: 1,
      loginId: "dpkk",
      userName: null,
      firstName: "Deepak",
      middleName: "lal",
      lastName: "lal",
      userGroupName: null,
      roleName: null,
      email: "d@gmail.com",
      phoneNo: "923636363636",
      mobileNo: "926363636363",
      address: "abc",
      roleId: 2,
      passwordPolicyId: 1,
      passwordExpireAt: null,
      retryCount: null,
      lastLoginAt: null,
      userGroupId: null,
      pageIndex: 0,
      pageRecord: 0,
      orderBy: null,
      sortType: null,
      password: null,
      createdBy: null,
      createdAt: null,
      confirmPassword: null,
      otpMatcher: null,
      locked: false,
      active: true,
      passwordChange: false,
    },
  };

  Roles = {
    ResponseCode: "00",
    Data: {
      roleName: "admin",
      description: "Hello Admin",
      sortOrder: null,
      roleDetail: null,
      active: true,
    },
  };

  PasswordPolicy = {
    ResponseCode: "00",
    Data: {
      passwordPolicyId: 5,
      minCapLetter: 2,
      minSmallLetter: 2,
      minNumber: 4,
      minLength: 8,
      allowedSpecialChar: "@",
      policyName: "Kuch b",
      expireDays: 5,
      maxRetryCount: 1,
      regularExp: null,
      pageIndex: 0,
      pageRecord: 0,
      active: true,
    },
  };

  Login = {
    access_token: "-ejY0JUVNaHD3w10MPUfnqr67T4",
    token_type: "bearer",
    refresh_token: "_ztTM4KbX2xP4NE5KWpQz3S4Muw",
    expires_in: 1199,
    scope: "read write trust",
    userTypeId: 1,
    isForcePassChanged: false,
    isPasswordExpired: false,
    userName: "Mubbsahir Kaim Khani",
    userId: 1,
  };

  Country = {
    ResponseCode: "00",
    Data: {
      countryId: 11,
      countryName: "Azad",
      isActive: true,
      createdBy: 1,
      createdAt: "2022-07-19T12:25:16.611Z",
      updatedBy: null,
      updatedAt: null,
      pageIndex: 0,
      pageRecord: 0,
    },
  };

  City = {
    ResponseCode: "00",
    Data: {
      cityId: 11,
      cityName: "Karachi",
      countryId: 11,
      isActive: true,
      createdBy: 1,
      createdAt: "2022-07-19T12:25:16.611Z",
      updatedBy: null,
      updatedAt: null,
      pageIndex: 0,
      pageRecord: 0,
    },
  };
  State = {
    ResponseCode: "00",
    Data: {
      stateId: 1,
      countryId: 1,
      cityId: 1,
      stateName: "United Arab1",
      countryName: "Pakistan",
      cityName: "Karachi",
      isActive: true,
      createdBy: 1,
      createdAt: "2021-10-27T23:16:16.794Z",
      updatedBy: 6,
      updatedAt: "2022-06-06T06:58:47.769Z",
      pageIndex: 0,
      pageRecord: 0,
      countryEntity: null,
      stateEntity: null,
    },
  };
  Institution = {
    ResponseCode: "00",
    Data: {
      institutionId: 5,
      institutionName: "XYZ1",
      institutionDescription: "XYZ1",
      contactPersonName: "Ali Raza Katri",
      contactPersonPhone: "03143543458",
      contactPersonNic: "41302247895147",
      contactPersonEmail: "aliraza@gmail.com",
      isActive: false,
      createdBy: 6,
      createdAt: "2022-06-09T07:07:50.804Z",
      updatedBy: 6,
      updatedAt: "2022-06-09T07:08:03.148Z",
      pageIndex: 0,
      pageRecord: 0,
    },
  };
  FeeType = {
    ResponseCode: "00",
    Data: {
      feeTypeId: 4,
      feeTypeName: "tution1",
      beneficiary: "Beneficiary",
      processByTxn: "yes",
      includeVAT: "yes",
      commissionFee: "no",
      useCase: "send Money",
      feeType: "testFeeType",
      institutionUnitPayee: "vanila",
      payeeFee: "yes",
      institutionUnitPayer: "soapUi",
      subTxnType: "Authoristion",
      piTypePayee: "System SVA",
      copyFromAuth: "yes",
      piTypePayer: "unit Trust",
      includeInLimit: "yes",
      isActive: false,
      createdBy: 6,
      createdAt: "2022-06-09T07:11:19.288Z",
      updatedBy: null,
      updatedAt: null,
      pageIndex: 0,
      pageRecord: 0,
    },
  };
  AccountType = {
    ResponseCode: "00",
    Data: {
      accountTypeId: 3,
      accountTypeName: "ABC1",
      accountTypeDescription: "ABC1",
      isActive: false,
      createdBy: 6,
      createdAt: "2022-06-09T07:50:06.339Z",
      updatedBy: 6,
      updatedAt: "2022-06-09T07:50:16.989Z",
      pageIndex: 0,
      pageRecord: 0,
    },
  };

  CustomerType = {
    ResponseCode: "00",
    Data: {
      customerTypeId: 1,
      customerTypeName: "kawish crown bank",
      customerTypeDescription: "hello kawish crown bank",
      isActive: false,
      createdBy: 1,
      createdAt: "2022-06-08T12:04:27.832Z",
      updatedBy: 6,
      updatedAt: "2022-06-09T07:16:39.888Z",
      pageIndex: 0,
      pageRecord: 0,
    },
  };
  UseCase = {
    ResponseCode: "00",
    Data: {
      useCaseId: 2,
      useCaseName: "Bank-Al-habib",
      description: "Nothing",
      isActive: true,
      createdBy: 1,
      createdAt: "2022-06-09T07:20:57.302Z",
      updatedBy: null,
      updatedAt: null,
      pageIndex: 0,
      pageRecord: 0,
    },
  };
  GlAccount = {
    ResponseCode: "00",
    Data: {
      glAccountId: 1,
      glAccountName: "kawish crown bank",
      glAccountNumber: "10001222999",
      glAccountType: "regular",
      isActive: false,
      createdBy: 1,
      createdAt: "2022-06-09T09:53:23.520Z",
      updatedBy: 1,
      updatedAt: "2022-06-11T08:07:40.912Z",
      pageIndex: 0,
      pageRecord: 0,
    },
  };
  RiskCategory = {
    ResponseCode: "00",
    Data: {
      riskCategoryId: 6,
      riskCategoryName: "Mubbashir",
      riskCategoryDescription: "Kaim khani",
      isActive: false,
      createdBy: 1,
      createdAt: "2022-06-22T09:31:08.668Z",
      updatedBy: 1,
      updatedAt: "2022-06-22T10:36:30.771Z",
      pageIndex: 0,
      pageRecord: 0,
    },
  };
  LimitSet = {
    ResponseCode: "00",
    Data: {
      limitSetConfigurationId: 4,
      limitSetConfigurationName: "chal bhag",
      limitSetConfigurationDescription: "hahha",
      isActive: true,
      createdBy: 1,
      createdAt: "2022-06-23T05:30:19.225Z",
      updatedBy: null,
      updatedAt: null,
      pageIndex: 0,
      pageRecord: 0,
    },
  };
  FeeSet = {
    ResponseCode: "00",
    Data: {
      feeSetConfigurationId: 2,
      feeSetConfigurationName: "meezan",
      useCaseId: "use case no 1",
      currency: "Euro",
      feeType: 1,
      threshold: "0.00",
      min: "0.05",
      max: "50",
      onTop: "0.00",
      percentage: "5",
      feeSetConfigurationDescription: "meezan bank limited",
      isActive: true,
      createdBy: 1,
      createdAt: "2022-07-26T07:47:26.642Z",
      updatedBy: null,
      updatedAt: null,
      pageIndex: 0,
      pageRecord: 0,
    },
  };

  ApprovedCustomer = {
    ResponseCode: "00",
    Data: {
      customerId: 17,
      firstName: "Shahbaz",
      lastName: "Arain",
      contactNo: "03124747484",
      gender: "Male",
      language: "English",
      city: "New York",
      dateOfBirth: "8/24/2022",
      country: "USA",
      state: "California",
      houseNo: "G/2535",
      streetAddressNo1: "New Sardar Colony",
      streetAddressNo2: "near hirabad",
      email: "mubbashirk8@gmail.com",
      modeInfo: "Email",
      customerType: 1,
      feeSetId: 1,
      limitSetId: 1,
      institutionId: 1,
      isActive: true,
      makerComment: "this user is legal",
      checkerComment: "this user is Illegal",
      createdBy: 1,
      status: "approved",
      createdAt: "2022-07-20T07:05:19.650Z",
      updatedBy: null,
      updatedAt: null,
      pageIndex: 0,
      pageRecord: 0,
    },
  };

  PendingCustomer = {
    ResponseCode: "00",
    Data: {
      checkerMakerId: 12,
      useCase: "use case no 1",
      jsonData:
        '{"customerId": 17,"firstName": "Shahbaz","lastName": "Arain","contactNo": "03124747484","gender": "Male","language": "English","city": "Hyderabad","dateOfBirth": "8/24/2022","country": "Pakistan","state": "UAE","houseNo": "G/2535","streetAddressNo1": "New Sardar Colony","streetAddressNo2": "near hirabad","email": "mubbashirk8@gmail.com","modeInfo": "Email","customerType": "customer type 1","isActive": true,"makerCheckerComment" : "Hello Approved Customer","createdBy": 1,"createdAt": "2022-07-20T07:05:19.650Z","updatedBy": null,"updatedAt": null,"pageIndex": 0,"pageRecord": 0 ,"feeSetId":"Fee set no 1","limitSetId":"limit set no 1" }',
      moduleType: "customer",
      status: "pending",
      makerCheckerComment: "Hello Customer 2",
      param1: null,
      param2: null,
      param3: null,
      institutionId: 1,
      createdBy: 1,
      createdAt: "2022-07-22T09:24:24.084Z",
      updatedBy: null,
      updatedAt: null,
    },
  };

  ReturnCustomer = {
    ResponseCode: "00",
    Data: {
      checkerMakerId: 9,
      // "useCase": "use case no 1",
      jsonData:
        '{"customerId": 17,"firstName": "Shahbaz","lastName": "Arain","contactNo": "03124747484","gender": "Male","language": "English","city": "Hyderabad","dateOfBirth": "8/24/2022","country": "Pakistan","state": "UAE","houseNo": "G/2535","streetAddressNo1": "New Sardar Colony","streetAddressNo2": "near hirabad","email": "mubbashirk8@gmail.com","modeInfo": "Email","customerType": 1,"isActive": true,"makerCheckerComment" : "Hello Approved Customer","createdBy": 1,"createdAt": "2022-07-20T07:05:19.650Z","updatedBy": null,"updatedAt": null,"pageIndex": 0,"pageRecord": 0 ,"feeSetId":1 ,"limitSetId":1 }',
      moduleType: "customer",
      status: "return",
      makerCheckerComment: "hello Comment ",
      checkerComment: "Customer Date of Birth is InCorrect",
      makerComment: "Customer Date of Birth is Correct",
      param1: "03124578879",
      param2: null,
      param3: null,
      institutionId: 1,
      createdBy: 1,
      createdAt: "2022-07-20T07:07:07.185Z",
      updatedBy: 1,
      updatedAt: "2022-07-22T09:43:24.990Z",
    },
  };

  LimitClasses = {
    ResponseCode: "00",
    Data: {
      limitClassesId: 9,
      limitClassName: "Test Limit Class",
      dailyDebitLimitCount: "9,999,999,999,999",
      weeklyDebitLimitCount: "9,999,999,999,999",
      monthlyDebitLimitCount: "9,999,999,999,999",
      absoluteDebitLimitCount: "9,999,999,999,999",
      dailyCreditLimitCount: "9,999,999,999,999",
      weeklyCreditLimitCount: "9,999,999,999,999",
      monthlyCreditLimitCount: "9,999,999,999,999",
      absoluteCreditLimitCount: "9,999,999,999,999",
      singleDebitLimitAmount: "9,999,999,999,999",
      singleCreditLimitAmount: "9,999,999,999,999",
      currency: "Euro",
      dailyDebitLimit: "9,999,999,999,999",
      weeklyDebitLimit: "9,999,999,999,999",
      monthlyDebitLimit: "9,999,999,999,999",
      absoluteDebitLimit: "9,999,999,999,999",
      dailyCreditLimit: "9,999,999,999,999",
      weeklyCreditLimit: "9,999,999,999,999",
      monthlyCreditLimit: "9,999,999,999,999",
      absoluteCreditLimit: "9,999,999,999,999",
      singleMinimumDebit: "",
      singleMinimumCredit: "",
      createdBy: 1,
      createdAt: "2022-07-20T07:07:07.185Z",
      updatedBy: 1,
      updatedAt: "2022-07-22T09:43:24.990Z",
    },
  };

  CustomeAccount = {
    ResponseCode: "00",
    Data: {
      customerAccountId: "1",
      accountTitle: "current",
      accountNumber: "034954785554441",
      customerId: "customer 1",
      limitSetId: "limit set 1",
      feeSetId: "Fee set 1",
    },
  };

  AuthorizationMatrix = {
    ResponseCode: "00",
    Data: {
      customerId: 18,
      useCase: 2,
      institution: "Meezan",
      method: 1,
      flowSequence: "2",
      result0: "4",
      result1: "5",
      result2: "6",
      result3: "8",
      result4: "9",
      "authorizationMatrix ": "",
      createdBy: 1,
      createdAt: "2022-07-22T09:24:24.081Z",
      updatedBy: 1,
      updatedAt: "2022-07-22T09:24:24.081Z",
    },
  };

  LimitSetClass = {
    ResponseCode: "00",
    Data: {
      id: 2,
      limitSetClassName: "Meezan",
      limitSetId: 1,
      limitClassId: 2,
      useCaseId: 1,
      institution: 5,
      createdBy: 1,
      createdAt: "2022-07-22T09:24:24.081Z",
      updatedBy: 1,
      updatedAt: "2022-07-22T09:24:24.081Z",
    },
  };

  BlackListReason = {
    ResponseCode: "00",
    Data: {
      reasonId: 2,
      reasonName: "Reason name one",
      blackReasonDescription: "Description no 1",
      institution: 4,
      revokedRole: 1,
      isActive: true,
      createdBy: 1,
      createdAt: "2022-06-22T09:31:08.668Z",
      updatedBy: 1,
      updatedAt: "2022-06-22T10:36:30.771Z",
      pageIndex: 0,
      pageRecord: 0,
    },
  };
  BackOfficeTransaction = {
    ResponseCode: "00",
    Data: {
      backOfficeTransactionId: 2,
      institution: "Dubai Islamic Bank Limited",
      searchTransferType: 2,
      debitIdentityType: 2,
      debitAccount: "2500",
      creditIdentityType: 2,
      creditAccount: "2000",
      amount: "15000",
      status: "approved",
      transactionDescription: "Transaction Description",
      makerComment: "this user is legal",
      checkerComment: "this user is Illegal",
      createdBy: 1,
      createdAt: "2022-07-22T09:24:24.081Z",
      updatedBy: null,
      updatedAt: null,
      pageIndex: 0,
      pageRecord: 0,
    },
  };
  ApprovedBackOfficeTransaction = {
    ResponseCode: "00",
    Data: {
      backOfficeTransactionId: 4,
      institution: "Samba Bank",
      searchTransferType: "4",
      searchTransferTypeName: "Wallet To Wallet",
      debitIdentityType: "ntn",
      debitAccount: "5757276",
      debitAccountName: "5757276",
      creditIdentityType: "nic",
      creditAccount: "4130204143332",
      creditAccountName: "4130204143332",
      amount: "15000",
      status: "Approved",
      transactionDescription: "Transaction Description",
      actionPerformed: "Updated",
      makerComment: "this user is legal",
      checkerComment: "this user is ilegal",
      createdBy: 1,
      createdAt: "2022-07-22T09:24:24.081Z",
      updatedBy: null,
      updatedAt: null,
      pageIndex: 0,
      pageRecord: 0,
    },
  };
  tax = {
    ResponseCode: "00",
    Data: {
      taxId: 3,
      taxName: "WithHolding",
      institutionId: 15,
      description: "With holding Tax",
      isActive: true,
      inclusive: false,
      glAccountId: 1,
      institutionName: "IPath",
      glAccountName: "Cutomer Debit",
      stateId: 72,
      createdBy: 1,
      createdAt: "2022-07-26T07:47:26.642Z",
      updatedBy: null,
      updatedAt: null,
      pageIndex: 0,
      pageRecord: 0,
    },
  };
  stateTaxConfiguration = {
    ResponseCode: "00",
    Data: {
      stateTaxConfigurationId: 2,
      institutionId: 26,
      stateId: 71,
      taxId: 3,
      useCaseId: 40,
      isActive: true,
      createdBy: 6,
      createdAt: "2023-12-13T08:16:37.509Z",
      institutionName: "VRG",
      stateName: "Sindh",
      taxName: "WithHolding",
      useCaseName: "SCB Customer To Gl Test",
    },
  };
}
