

import { NgModule } from "@angular/core";
import { DummyTableComponent } from "./components/dummy-table/dummy-table.component";
import { MaterialUiModule } from "./material-ui.module";
import { CommonModule, NgClass } from "@angular/common";
import { BrowserModule } from "@angular/platform-browser";
import { AppComponent } from "./app.component";
import { AppRoutingModule } from "./app-routing.module";
import { BrowserAnimationsModule } from "@angular/platform-browser/animations";
import { HttpClientModule } from "@angular/common/http";
import { ApiService } from "../services/api.service";
import { DummyPageComponent } from "./components/dummy-page/dummy-page.component";
import { DummyExpandableTableComponent } from "./components/dummy-expandable-table/dummy-expandable-table.component";
import { ManageInstitutionListComponent } from "./administration/manage-institution-list/manage-institution-list.component";
import { AddInstitutionDetailsComponent } from "./administration/manage-institution-list/add-institution-details/add-institution-details.component";
import { ManageGlobalConfigurationListComponent } from "./administration/manage-global-configuration-list/manage-global-configuration-list.component";
import { ManageChannelsListComponent } from "./administration/manage-channels-list/manage-channels-list.component";
import { AddChannelDetailsComponent } from "./administration/manage-channels-list/Add-Form-Fields/add-channel-details/add-channel-details.component";
import { AddGlobalConfigurationComponent } from "./administration/manage-global-configuration-list/add-global-configuration/add-global-configuration.component";
import { ManageChannelDetailsComponent } from "./administration/manage-channels-list/manage-channel-details/manage-channel-details.component";
import { AddCustomFieldDetailsComponent } from "./administration/manage-channels-list/Add-Form-Fields/add-custom-field-details/add-custom-field-details.component";
import { AddEndpointDetailsComponent } from "./administration/manage-channels-list/Add-Form-Fields/add-endpoint-details/add-endpoint-details.component";
import { AddFieldMappingDetailsComponent } from "./administration/manage-mapping-channels-list/Add-Form-Fields/add-field-mapping-details/add-field-mapping-details.component";
import { AddMessageInitializationDetailsComponent } from "./administration/manage-channels-list/Add-Form-Fields/add-message-initialization-details/add-message-initialization-details.component";
import { AddProcessingRuleDetailsComponent } from "./administration/manage-mapping-channels-list/Add-Form-Fields/add-processing-rule-details/add-processing-rule-details.component";
import { AddQueuesDetailsComponent } from "./administration/manage-channels-list/Add-Form-Fields/add-queues-details/add-queues-details.component";
import { AddServicesDetailsComponent } from "./administration/manage-channels-list/Add-Form-Fields/add-services-details/add-services-details.component";
import { AddMessageRoutingDetailsComponent } from "./administration/manage-mapping-channels-list/Add-Form-Fields/add-message-routing-details/add-message-routing-details.component";
import { AddFieldDefinitionComponent } from "./administration/manage-channels-list/Add-Form-Fields/add-field-definition/add-field-definition.component";
import { MatDialogModule } from "@angular/material/dialog";
import { ViewEndpointDetailsDialogComponent } from "./administration/manage-channels-list/View-Dialog-Boxes/view-endpoint-details-dialog/view-endpoint-details-dialog.component";
import { AdminLayoutComponent } from "./elements/admin-layout/admin-layout.component";
import { RouterOutlet } from "@angular/router";
import { ChatboxComponent } from "./elements/chatbox/chatbox.component";
import { FooterComponent } from "./elements/footer/footer.component";
import { HeaderComponent } from "./elements/header/header.component";
import { NavHeaderComponent } from "./elements/nav-header/nav-header.component";
import { SidebarComponent } from "./elements/sidebar/sidebar.component";
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { ManageMappingChannelsListComponent } from "./administration/manage-mapping-channels-list/manage-mapping-channels-list.component";
import { ManageMappingChannelsDetailsComponent } from "./administration/manage-mapping-channels-list/manage-mapping-channels-details/manage-mapping-channels-details.component";
import {MatTreeModule} from '@angular/material/tree';
import {MatIconModule} from '@angular/material/icon';
import {MatButtonModule} from '@angular/material/button';
import { PreviewChannelMappingsComponent } from "./administration/preview-channel-mappings/preview-channel-mappings.component";
import { PreviewMessageFieldMappingComponent } from "./administration/preview-channel-mappings/preview-message-field-mapping/preview-message-field-mapping.component";
import { PreviewMessageRoutingComponent } from "./administration/preview-channel-mappings/preview-message-routing/preview-message-routing.component";
@NgModule({
    declarations: [
        PreviewMessageFieldMappingComponent,
        PreviewMessageRoutingComponent,
        PreviewChannelMappingsComponent, 
        NavHeaderComponent,
        ChatboxComponent,
        HeaderComponent,
        SidebarComponent,
        FooterComponent,
        AdminLayoutComponent,
AppComponent,
        ManageMappingChannelsListComponent,
        ManageMappingChannelsDetailsComponent,
        DummyTableComponent,
        DummyPageComponent,
        AppComponent,
        DummyExpandableTableComponent,
        ManageInstitutionListComponent,
        AddInstitutionDetailsComponent,
        ManageGlobalConfigurationListComponent,
        ManageChannelsListComponent,
        AddChannelDetailsComponent,
        ManageChannelDetailsComponent,
        AddGlobalConfigurationComponent,
        AddCustomFieldDetailsComponent,
        AddEndpointDetailsComponent,
        AddFieldMappingDetailsComponent,
        AddMessageInitializationDetailsComponent,
        AddProcessingRuleDetailsComponent,
        AddQueuesDetailsComponent,
        AddServicesDetailsComponent, 

        AddMessageRoutingDetailsComponent,
        AddFieldDefinitionComponent, 
        ViewEndpointDetailsDialogComponent 
        /*   FullComponent,
  
        AdminComponent,
        Index1Component,
        Index2Component,
        LoadingComponent,
        NavHeaderComponent,
        NavigationComponent,
        HeaderComponent,
        FooterComponent,

        ProfileComponent,
        UserStatisticsComponent,
        InterestComponent,
        LatestNewsComponent,
        HighlightsComponent,

        PostDetailsComponent,

        ComposeComponent,
        InboxComponent,
        ReadComponent,

        CalenderComponent,

        ProductGridComponent,
        ProductListComponent,
        ProductDetailComponent,
        OrderComponent,
        CheckoutComponent,
        InvoiceComponent,
        EcomCustomersComponent,

        ApexComponent,
        LineComponent,
        BasicLineChartComponent,
        LineChartWithDatalabelsComponent,
        ZoomableTimeseriesComponent,
        LineWithAnnotationsComponent,
        SyncingChartsComponent,
        BrushChartComponent,
        SteplineChartComponent,
        GradientLineChartComponent,
        MissingOrNullValuesComponent,
        DashedLineChartComponent,
        AreaComponent,
        AreaBasicComponent,
        AreaNegativeComponent,
        AreaGithubStyleComponent,
        AreaSplineComponent,
        AreaStackedComponent,
        AreaIrregularTimeseriesComponent,
        AreaMissingOrNullValuesComponent,

        ColumnComponent,
        ColumnBasicComponent,
        ColumnDataLabelsComponent,
        ColumnStackedComponent,
        ColumnStacked100Component,
        ColumnRotatedLabelsComponent,
        ColumnNegativeValuesComponent,
        ColumnLoadedChartComponent,
        ColumnDistributedComponent,
        ColumnRangeComponent,

        BarComponent,
        BarBasicComponent,
        BarGroupedComponent,
        BarStackedComponent,
        BarStacked100Component,
        BarNegativeValuesComponent,
        BarReversedComponent,
        BarCustomDataLabelsComponent,
        BarPatternedComponent,
        BarImagesComponent,

        MixedComponent,
        MixedLineColumnComponent,
        MixedMultipleYAxisComponent,
        MixedLineAreaComponent,
        MixedLineColumnAreaComponent,

        TimelineComponent,
        TimelineBasicComponent,
        TimelineDistributedComponent,
        TimelineMultiSeriesComponent,
        TimelineAdvancedComponent,
        TimelineMultipleSeriesComponent,

        CandlestickComponent,
        CandlestickBasicComponent,
        CandlestickComboComponent,
        CandlestickCategoryComponent,
        CandlestickLineComponent,

        PieComponent,
        PieSimpleComponent,
        PieDonutComponent,
        PieMonochromeComponent,
        PieGradientDonutComponent,
        SemiDonutComponent,
        DonutWithPatternComponent,

        RadarComponent,
        RadarBasicComponent,
        RadarMultipleSeriesComponent,

        RadialbarComponent,
        RadialbarBasicComponent,
        RadialbarMultipleComponent,
        RadialbarCustomAngleCircleComponent,
        RadialbarGradientComponent,
        RadialbarStrokedAngularGaugeComponent,
        RadialbarSemiCircleGaugeComponent,

        PolarAreaComponent,
        PolarAreaBasicComponent,
        PolarAreaMonochromeComponent,

        BubbleComponent,
        BubbleSimpleComponent,
        Bubble3DComponent,

        ScatterComponent,
        ScatterBasicComponent,
        ScatterDatetimeComponent,
        ScatterImagesComponent,

        HeatmapComponent,
        HeatmapBasicComponent,
        HeatmapMultipleColorsComponent,
        HeatmapMultipleFlippedComponent,
        HeatmapColorRangeComponent,
        HeatmapRoundedComponent,

        TreemapComponent,
        TreemapBasicComponent,
        TreemapMultipleSeriesComponent,
        TreemapColorRangeComponent,
        TreemapDistributedComponent,

        SparklinesComponent,
        SparklinesBasicComponent,

        ChartjsComponent,
        ChartjsLineComponent,
        ChartjsBarComponent,
        ChartjsDoughnutComponent,
        ChartjsRadarComponent,
        ChartjsPieComponent,
        ChartjsBubbleComponent,



        AccordionComponent,
        AccordionBasicComponent,
        AccordionStaticComponent,
        AccordionToggleComponent,
        AccordionHeaderComponent,
        AccordionPreventchangeComponent,
        AccordionConfigComponent,
        AlertComponent,
        AlertCloseableComponent,
        AlertBasicComponent,
        AlertSlefclosingComponent,
        AlertCustomComponent,
        AlertConfigComponent,
        ButtonComponent,
        ModalComponent,
        BasicModalComponent,
        ModalComponentComponent,
        ModalOptionsComponent,
        ModalFocusComponent,
        ModalStackedComponent,
        ModalConfigComponent,
        BadgeComponent,
        ButtonGroupComponent,
        ListGroupComponent,
        CarouselComponent,
        CarouselBasicComponent,
        CarouselNavigationComponent,
        CarouselPauseComponent,
        CarouselConfigComponent,

        DatepickerComponent,
        DatepickerBasicComponent,
        DatepickerPopupComponent,
        DatepickerMultipleComponent,
        DatepickerRangeComponent,
        DatepickerRangePopupComponent,
        DatepickerDisabledComponent,
        DatepickerAdapterComponent,
        DatepickerCustommonthComponent,
        DatepickerFootertemplateComponent,
        DatepickerPositiontargetComponent,
        DatepickerKeyboardComponent,

        DropdownComponent,
        DropdownBasicComponent,
        DropdownManualComponent,
        DropdownSplitComponent,
        DropdownFormComponent,
        DropdownContainerComponent,
        DropdownNavbarComponent,
        DropdownConfigComponent,
        MediaObjectComponent,
        NavComponent,
        NavMarkupComponent,
        NavVerticalComponent,
        NavSelectionComponent,
        NavKeepContentComponent,
        NavDynamicComponent,
        NavCustomStyleComponent,
        NavConfigComponent,
        NavBasicComponent,
        PaginationComponent,
        PaginationBasicComponent,
        PaginationAdvancedComponent,
        PaginationCustomizationComponent,
        PaginationSizeComponent,
        PaginationJustifyComponent,
        PaginationDisabledComponent,
        PaginationConfigComponent,
        PopoverComponent,
        PopoverBasicComponent,
        PopoverTplcontentComponent,
        PopoverTriggersComponent,
        PopoverAutocloseComponent,
        PopoverTplwithcontextComponent,
        PopoverDelayComponent,
        PopoverVisibilityComponent,
        PopoverContainerComponent,
        PopoverCustomclassComponent,
        PopoverConfigComponent,
        ProgressbarComponent,
        ProgressbarBasicComponent,
        ProgressbarTexttypesComponent,
        ProgressbarShowvalueComponent,
        ProgressbarStripedComponent,
        ProgressbarLabelsComponent,
        ProgressbarHeightComponent,
        ProgressbarConfigComponent,
        RatingComponent,
        RatingBasicComponent,
        RatingEventsComponent,
        RatingTemplateComponent,
        RatingDecimalComponent,
        RatingFormComponent,
        RatingConfigComponent,
        TableComponent,
        TableBasicComponent,
        TableFilteringComponent,
        TablePaginationComponent,
        // NgbdSortableHeader,

        TimepickerComponent,
        TimepickerBasicComponent,
        TimepickerMeridianComponent,
        TimepickerSecondsComponent,
        TimepickerSpinnersComponent,
        TimepickerStepsComponent,
        TimepickerAdapterComponent,
        TimepickerConfigComponent,

        ToastComponent,
        ToastInlineComponent,
        ToastCustomComponent,
        ToastCloseableComponent,
        ToastPreventAutohideComponent,
        ToastGlobalComponent,
        ToastsContainer,

        TooltipComponent,
        TooltipBasicComponent,
        TooltipTplcontentComponent,
        TooltipTriggersComponent,
        TooltipAutocloseComponent,
        TooltipTplwithcontextComponent,
        TooltipDelayComponent,
        TooltipContainerComponent,
        TooltipCustomclassComponent,
        TooltipConfigComponent,

        TypeaheadComponent,
        TypeaheadBasicComponent,
        TypeaheadFocusComponent,
        TypeaheadFormatComponent,
        TypeaheadTemplateComponent,
        TypeaheadPreventManualEntryComponent,
        TypeaheadConfigComponent,
        CardsComponent,
        TypographyComponent,
        GridComponent,



        DzmtAutocompleteComponent,
        DzmtAutocompleteDisplayComponent,
        DzmtAutocompleteFilterComponent,
        DzmtAutocompleteFirstActiveComponent,
        DzmtAutocompleteOptgroupComponent,
        DzmtAutocompleteOverviewComponent,
        DzmtAutocompletePlaneComponent,
        DzmtAutocompleteSimpleComponent,

        DzmtBadgeComponent,
        DzmtBottomSheetComponent,
        DzmtButtonComponent,
        DzmtButtonBasicComponent,
        DzmtButtonVarietiesComponent,
        DzmtButtonToggleComponent,
        ButtonToggleAppearanceComponent,
        ButtonExclusiveSelectionComponent,
        ButtonWithFormsComponent,
        ButtonBasicTogglesComponent,

        DzmtCardComponent,
        CardMultipleSectionsComponent,
        CardBasicComponent,

        DzmtCheckboxComponent,
        ConfigurableCheckboxComponent,
        BasicCheckboxComponent,
        DzmtChipsComponent,
        ChipsAutocompleteComponent,
        ChipsDragDropComponent,
        ChipsWithInputComponent,
        ChipsBasicComponent,
        ChipsStackedComponent,

        DzmtDatepickerComponent,
        ComparisonRangesComponent,
        FormsIntegrationComponent,
        BasicDateRangeComponent,
        RangeCustomSelectionStrategyComponent,
        DatepickerActionButtonsComponent,
        DatepickerOpenMethodComponent,
        DatepickerPaletteColorsComponent,
        DatepickerCustomCalendarHeaderComponent,
        DatepickerCustomDateClassesComponent,
        DisabledDatepickerComponent,
        InputChangeEventsComponent,
        DatepickerFilterValidationComponent,
        DatepickerMinMaxValidationComponent,
        BasicDatepickerComponent,
        DatepickerStartDateComponent,
        DatepickerTouchUiComponent,
        DatepickerSelectedValueComponent,

        DzmtDialogComponent,

        HeaderScrollbarActionComponent,
        DialogContentExampleDialog,

        InjectingDataComponent,
        DialogDataExampleDialog,

        DialogElementsComponent,
        DialogElementsExampleDialog,

        DialogFromMenuComponent,
        DialogFromMenuExampleDialog,

        DialogOverviewComponent,
        DialogOverviewExampleDialog,

        DzmtDividerComponent,

        DzmtExpansionComponent,
        ExpandCollapseAllTogglesComponent,
        BasicExpansionPanelComponent,
        ExpansionAsAccordionComponent,

        DzmtFormFieldComponent,
        AppearanceVariantsComponent,
        FieldWithErrorMessagesComponent,
        FieldWithHintsComponent,
        FieldWithLabelComponent,
        SimpleFormFieldComponent,
        FieldWithPrefixSuffixComponent,
        FieldThemingComponent,

        DzmtGridListComponent,
        DynamicGridListComponent,
        BasicGridListComponent,

        DzmtIconComponent,
        SvgIconComponent,

        DzmtInputComponent,
        InputWithClearButtonComponent,
        InputErrorStateMatcherComponent,
        InputWithErrorMessageComponent,
        InputsInFormComponent,
        InputsWithHintsComponent,
        InputsBasicComponent,
        InputsWithPrefixesSuffixesComponent,

        DzmtListComponent,
        BasicListComponent,
        ListWithSectionsComponent,
        ListWithSelectionComponent,
        ListWithSingleSelectionComponent,

        DzmtMenuComponent,
        MenuWithIconsComponent,
        NestedMenuComponent,
        BasicMenuComponent,
        MenuPositioningComponent,

        DzmtPaginatorComponent,
        ConfigurablePaginatorComponent,
        BasicPaginatorComponent,

        DzmtProgressBarComponent,
        BufferProgressBarComponent,
        ConfigurableProgressBarComponent,
        DeterminateProgressBarComponent,
        IndeterminateProgressBarComponent,
        QueryProgressBarComponent,

        DzmtProgressSpinnerComponent,
        ConfigurableProgressSpinnerComponent,
        BasicProgressSpinnerComponent,

        DzmtRadioComponent,
        RadiosWithNgModelComponent,
        RadiosBasicComponent,
        DzmtRippleComponent,

        DzmtSelectComponent,
        CustomTriggerTextComponent,
        DisabledSelectComponent,
        CustomErrorStateMatcherComponent,
        SelectInFormComponent,
        SelectFormFieldFeaturesComponent,
        InitialValueNoFormComponent,
        MultipleSelectionComponent,
        NoOptionRippleComponent,
        OptionGroupsComponent,
        BasicSelectComponent,
        CustomPanelStylingComponent,
        SelectInReactiveFormComponent,
        SelectWithResetOptionComponent,
        TwoWayValueBindingComponent,

        DzmtSidenavComponent,
        AutosizeSidenavComponent,
        DrawerExplicitBackdropSettingComponent,

        DzmtSlideToggleComponent,
        ConfigurableSlideToggleComponent,
        SlideToggleWithFormsComponent,
        SlideToggleBasicComponent,

        DzmtSliderComponent,
        ConfigurableSliderComponent,
        CustomThumbLabelFormattingComponent,
        SliderBasicComponent,

        DzmtSnackBarComponent,
        SnackBarCustomComponentComponent,
        BasicSnackBarComponent,
        SnackBarConfigurableComponent,
        DzmtSortComponent,

        DzmtStepperComponent,
        EditableStepsComponent,
        DisplaysErrorsInStepsComponent,
        LabelBottomPositionComponent,
        OptionalStepsComponent,
        StepperOverviewComponent,
        StepperCustomizedStatesComponent,
        StepperVerticalComponent,

        DzmtTableComponent,
        BasicTableComponent,
        DynamicallyChangingColumnsDisplayedComponent,
        TableExpandableRowsComponent,
        TableWithFilteringComponent,
        TableWithDisplayFlexComponent,
        FooterRowTableComponent,
        RetrievingDataThroughHttpComponent,
        MultipleHeaderFooterRowsComponent,
        DataTableSortingPaginationFilteringComponent,
        TableWithPaginationComponent,
        TableWithReOrderableColumnsComponent,
        TableContextPropertiesComponent,
        TableWithSelectionComponent,
        TableWithSortingComponent,
        TableWithStickyColumnsComponent,
        TableWithToggleAbleStickyHeadersFootersColumnsComponent,
        TableFlexWithToggleAbleStickyHeadersFootersColumnsComponent,
        TableStickyFooterComponent,
        TableStickyHeaderComponent,
        TableWithConfigurationsInterfaceComponent,
        TableWithSimpleTextHeaderFooterComponent,

        DzmtTabsComponent,
        AlignedLabelsComponent,
        TabGroupAnimationsComponent,
        AsynchronouslyLoadingTabContentsComponent,
        BasicTabGroupComponent,
        TabsWithCustomLabelTemplateComponent,
        TabsWithDynamicallyChangingTabsComponent,
        TabsWithDynamicHeightComponent,
        TabsWithHeadersOnBottomComponent,
        TabsWithContentLoadedLazilyComponent,
        TabsWithStretchedLabelsComponent,
        TabsWithThemeOptionsComponent,
        BasicUseOfTabNavBarComponent,

        DzmtTooltipComponent,
        TooltipAutoHidingComponent,
        TooltipWithCustomClassComponent,
        TooltipWithShowHideDelayComponent,
        TooltipCanBeDisabledComponent,
        TooltipManuallyShowHideComponent,
        TooltipWithChangingMessageComponent,
        TooltipWithHideShowDelayComponent,
        BasicTooltipComponent,
        TooltipWithCustomPositionComponent,

        DzmtTreeComponent,
        TreeWithCheckboxesComponent,
        TreeWithDynamicDataComponent,
        TreeWithFlatNodesComponent,
        TreeWithPartiallyLoadedDataComponent,
        TreeWithNestedNodesComponent,

        DzmtToolbarComponent,
        BasicToolbarComponent,
        MultiRowToolbarComponent,
        ToolbarOverviewComponent,

        LightGalleryComponent,

        WidgetComponent,
        Timeline1Component,
        Timeline2Component,
        Notifications1Component,
        Notifications2Component,
        MessageComponent,
        TodolistComponent,
        PieChart1Component,
        BarChart1Component,
        BarChart2Component,
        AreaChart1Component,
        VisitorActivityComponent,
        VisitorActivityDayComponent,
        VisitorActivityMonthComponent,
        VisitorActivityYearComponent,
        ChartjsActiveUsersComponent,
        BloodPressureComponent,
        HeartRateComponent,
        GlucoseRateComponent,
        ClolesterolComponent,
        BarChart3Component,
        AreaChart2Component,
        BarChart4Component,
        BarChart5Component,
        AreaChart3Component,
        BarChart6Component,
        MarketNowComponent,
        SalesAnalysisComponent,
        TopProducts1Component,
        TopProducts2Component,
        WeeklySalesComponent,
        SalesStatusComponent,
        AllSales1Component,
        AllSales2Component,

        ElementsComponent,
        FormValidateComponent,

        RegisterComponent,
        LoginComponent,
        LockScreenComponent,
        ForgotPasswordComponent,
        Error400Component,
        Error403Component,
        Error404Component,
        Error500Component,
        Error503Component,
        GraphProjectCreatedComponent,
        GraphNewClientsComponent,
        GraphMonthlyTargetComponent,
        GraphProjectReleasedComponent,
        GraphContactsAddedComponent,
        UpcomingProjectsComponent,
        RecentMessagesComponent,
        ActivityComponent,
        ProjectsComponent,
        ContactsComponent,
        MessagesComponent,
        KanbanComponent,

        SwitcherComponent,
        PrivacyPolicyComponent,
        ChangeUserPasswordComponent,
        ListInstitutionComponent,
        // DialogInviteUserComponent,
        NestableComponent,
        InstitutionManagmentComponent,
        FullComponent,
        // UserManagementComponent,
        // DialogAddUserComponent,
        // DialogEditUserComponent,
        // RoleManagementComponent,
        // AddRoleComponent,

        // ListAuditTrialComponent,
        // DialogViewAuditTrailComponent,
        // AuditTrialListComponent,
        DummyNetworkTreeComponent,
        DummyNetworkTabsComponent,
        // DashboardPageComponent,
        DummyNavComponent,
        ResetPasswordComponent,
        SrcComponent,
        DateTimePickerComponent,
       
        DateTimePickerComponent*/
    ],
    imports: [
        MatTreeModule,
        MatIconModule,
        MatButtonModule,
        NgbModule,
        MaterialUiModule,
        AppRoutingModule,
        BrowserModule,
        CommonModule,
        BrowserAnimationsModule,
        MatDialogModule,
        HttpClientModule 
    ],
   /*   exports:[DateTimePickerComponent], */
     providers: [
         /* {
             provide: LocationStrategy,
             useClass: HashLocationStrategy,
             
             // useClass: PathLocationStrategy
         },
         PreviousRouteService,
         SharedService, */
         ApiService,
       /*   { provide: MAT_DIALOG_DATA, useValue: {} },
         { provide: MatDialogRef, useValue: {} },
         OnlyLoggedInUserGuard,
         OnlyLoggedOutUserGuard, */
     ],
     bootstrap: [AppComponent] 
})
export class AppModule { }
